pentaho/pentaho-osgi-bundles

pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnection.java
Validated on a windows and mac environment
=> [BACKLOG-516] - Using the filename only to generate the manifest for the webjars bundle

pentaho-cache-manager/impl/ehcache/pom.xml, pentaho-cache-manager/impl/ehcache/src/main/java/org/pentaho/caching/ehcache/EhcacheProvidingService.java, pentaho-cache-manager/impl/ehcache/src/main/resources/OSGI-INF/blueprint/blueprint.xml, pentaho-cache-manager/impl/ehcache/src/test/java/org/pentaho/caching/ehcache/EhcacheProvidingServiceTest.java
PentahoCacheProvidingService for ehcache which supplies a JCache
CacheManager wrapping ehcache 2.x.  This provider will need to be
enhanced to support configuration of non-jcache covered features
(e.g. memory sizing and cache storage).
=> [BACKLOG-3358] A starting implementation of a

pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RebuildCacheCallable.java, pentaho-requirejs-osgi-manager/src/test/java/org/pentaho/js/require/RebuildCacheCallableTest.java
When duplicate requires are defined, absolute paths from require.json in a OSGI bundle are not properly converted to relative paths.
For review. @CodeOnCoffee @pentaho-nbaker
=> [BISERVER-12772] Ensure toRelativePathedObject is always called

pentaho-ss2-proxies/src/main/java/org/pentaho/proxy/creators/ProxyCreatorActivator.java, pentaho-ss2-proxies/src/main/java/org/pentaho/proxy/creators/grantedauthorities/GrantedAuthorityProxyCreator.java, pentaho-ss2-proxies/src/test/java/org/pentaho/proxy/creators/grantedauthorities/GrantedAuthorityProxyCreatorTest.java, pentaho-ss4-proxies/src/main/java/org/pentaho/proxy/creators/grantedauthorities/S4GrantedAuthorityProxyCreator.java, pentaho-ss4-proxies/src/main/resources/OSGI-INF/blueprint/beans.xml, pentaho-ss4-proxies/src/test/java/org/pentaho/proxy/creators/grantedauthorities/S4GrantedAuthorityProxyCreatorTest.java
Created a new ProxyCreator for the GrantedAuthority spring object
- there are situations where the GrantedAuthorities are being fetched directly ( i.e. being fetched from the IPentahoSession.SESSION_ROLES ) and not via a ( already proxy-wrapped ) UserDetails
- example: reports with a mondrian datasource: https://github.com/pentaho/pentaho-platform/blob/6.0.0.0-R/extensions/src/org/pentaho/platform/plugin/action/mondrian/mapper/MondrianAbstractPlatformUserRoleMapper.java#L153
- added unit tests
=> [BACKLOG-4439] Create SAML Implementation using Spring 4 as a Reference Implementation

pentaho-ss2-proxies/src/main/java/org/pentaho/proxy/creators/authenticationprovider/AuthenticationProxyCreator.java, pentaho-ss2-proxies/src/main/java/org/pentaho/proxy/creators/securitycontext/SecurityContextProxyCreator.java, pentaho-ss4-proxies/src/main/java/org/pentaho/proxy/creators/authenticationprovider/S4AuthenticationProxyCreator.java, pentaho-ss4-proxies/src/main/java/org/pentaho/proxy/creators/securitycontext/S4SecurityContextProxyCreator.java
- safeguarded SecurityContextProxyCreator / S4SecurityContextProxyCreator against possible NPE's ( when calls to SecurityContextHelper.getContext().setAuthentication( null ) are made )
- AuthenticationProxyCreator / S4AuthenticationProxyCreator so far only allowed for the proxy-wrapping of "UsernamePasswordAuthenticationToken"; I expanded it to also allow for the wrapping of "AnonymousAuthenticationToken" ( which is something that the anonymousAuthenticationFilterChain does
=> [BISERVER-12921] Implement Global Logout in SAML

pentaho-server-bundle/src/main/java/org/pentaho/platform/server/osgi/PentahoOSGIActivator.java, pentaho-server-bundle/src/test/java/org/pentaho/platform/server/osgi/PentahoOSGIActivatorTest.java
"org.pentaho.requirejs" configuration.
This way, when PentahoOSGIActivator creates the configuration (i.e.,
when there is no configuration with such a name), the location of this
configuration is consistent with the same configuration handled on the
blueprint file of project "pentaho-requirejs-osgi-manager".
=> [BACKLOG-4460] Added location "null" for the getConfiguration of

pentaho-ss2-proxies/src/main/java/org/pentaho/proxy/creators/userdetailsservice/ProxyUserDetailsService.java, pentaho-ss2-proxies/src/test/java/org/pentaho/proxy/creators/userdatailsservice/ProxyUserDetailsServiceTest.java, pentaho-ss4-proxies/src/main/java/org/pentaho/proxy/creators/userdetailsservice/S4UserDetailsServiceProxyCreator.java, pentaho-ss4-proxies/src/test/java/org/pentaho/proxy/creators/userdetailsservice/S4UserDetailsServiceProxyCreatorTest.java
UserDetailsService interface. When a UserDetails is not found, the
proxies will throw UsernameNotFoundException exception instead of
returning null. Moreover, they will be now expecting
UsernameNotFoundExceptions from the SourceObject, as well as, throwing
UsernameNotFoundException if SourceObject returns null.
=> [BACKLOG-6171] Modified SS2 and SS4 pentaho proxies to be according to

pentaho-i18n-bundle/src/main/java/org/pentaho/osgi/i18n/impl/LocalizationManager.java, pentaho-i18n-bundle/src/main/java/org/pentaho/osgi/i18n/resource/OSGIResourceBundle.java, pentaho-i18n-bundle/src/main/java/org/pentaho/osgi/i18n/resource/OSGIResourceBundleCacheCallable.java, pentaho-i18n-bundle/src/main/java/org/pentaho/osgi/i18n/settings/OSGIResourceNameComparator.java, pentaho-i18n-bundle/src/main/java/org/pentaho/osgi/i18n/settings/OSGIResourceNamingConvention.java, pentaho-i18n-bundle/src/test/java/org/pentaho/osgi/i18n/impl/LocalizationManagerTest.java, pentaho-i18n-bundle/src/test/java/org/pentaho/osgi/i18n/resource/OSGIResourceBundleCacheCallableTest.java, pentaho-i18n-bundle/src/test/java/org/pentaho/osgi/i18n/resource/OSGIResourceBundleTest.java, pentaho-i18n-bundle/src/test/java/org/pentaho/osgi/i18n/settings/OSGIResourceNameComparatorTest.java, pentaho-i18n-bundle/src/test/java/org/pentaho/osgi/i18n/settings/OSGIResourceNamingConventionTest.java, pentaho-i18n-bundle/src/test/resources/i18n/bundle/messages_fr.properties.2, pentaho-i18n-bundle/src/test/resources/i18n/bundle/messages_fr.properties.3, pentaho-i18n-bundle/src/test/resources/i18n/bundle/messages_fr.properties.4
Hierarchy of properties files is build according to their Locale and Priority.
Hierarchy starts with more detailed Locale and higher priority, so if we have following files, their hierarchy would be:
messages_en_US.properties
messages_en.properties.3
messages_en.properties
messages.properties.4
messages.properties.2
messages.properties Key is searched in properties starting with Locale you've asked and down. First key occurrence is used.
=> [BACKLOG-8306] - make properties files be merged with Locale&Priority

pom.xml
=> [BACKLOG-9079] - Removed Table Viz from lowdeps

pentaho-i18n-webservice-bundle/src/main/javascript/web/js/i18n.js
In the accept header of Firefox we don't have **"application/JSON"**, which is what **pentaho-i18n-webservice-bundle** is expecting. This wasn't happening in Chrome because the **accept header** set to accept anything.
@diogofscmariano @pentaho/kashyyyk please review
=> [BACKLOG-9894] DET: In Firefox - DET does not open ( only outside PDI )

pentaho-notification-webservice-bundle/pom.xml
@pamval @YuryBY please review. Adding `common-ui` as a test dependency and updating the version of the `jasmine-maven-plugin` test dependency allows the project `pentaho-notification-webservice-bundle` to build successfully after updating `angularjs` to version 1.5.8.
=> [PPP-3559] Update version of vulnerable component Angular.js 1.2.21

pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafBlueprintWatcherImpl.java, pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafFeatureWatcherImpl.java
Transient=true
We should to close the tracker because we need to shutdown framework before the app shutdown for clear cache folder. The runned service tracker causes the problem during shutdown.
please see https://issues.apache.org/jira/browse/FELIX-971
=> [BACKLOG-11614] Karaf temporary folders are not deleted in case of

pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnection.java, pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsUrlHandler.java, pentaho-webjars-deployer/src/main/resources/OSGI-INF/blueprint/blueprint.xml, pentaho-webjars-deployer/src/test/java/org/pentaho/osgi/platform/webjars/PentahoWebjarsTransformerTest.java, pentaho-webjars-deployer/src/test/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnectionTest.java
Webjar's javascript files minification have a significant impact when booting for the first time / with clean karaf caches.
| `time` | Empty caches, minification enabled | Empty caches, minification disabled | Full caches |
| --- | --- | --- | --- |
| real      | **1m 48.354s** | **1m  7.967s** | 0m 35.578s |
| user     | 3m 46.528s | 2m  9.372s | 1m 26.942s |
| sys       | 0m 20.522s | 0m 17.746s | 0m  5.418s |
It can become a little painful at development time when needing to restart the software a few times.
This PR adds a configuration property that allows disabling the minification. Webjars will be deployed only with its original source files.
- Create and edit the file `system/karaf/etc/org.pentaho.osgi.platform.webjars.cfg`
- Write `webjars.minification.enabled=false` and save
- …
=> [CLEANUP] Allows disabling minification

pentaho-zookeeper-fragment/pom.xml
DynamicImport-Package * instead of explicitly specifying log4j as it is
looking for other dependencies like javax.security etc.
=> [BACKLOG-15451] Modified the zookeeper fragment bundle to specify

pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsConfigManager.java
There are some cases (edge / IE) where the last modified property is being checked before any update to the caches is done. This breaks the browsers caching mechanism. Setting the last modified property to a sane value at the manager's creation fixes the issue.
@pentaho/millenniumfalcon @nantunes please review
=> [BACKLOG-15657] - Setting the last modified property to a sane value at the beginning of the manager creation.

pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/PlatformPluginBundlingURLConnection.java, pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/PlatformPluginMavenURLHandler.java, pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/PlatformPluginURLHandler.java, pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/impl/BundleStateManager.java, pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/impl/ManifestUpdaterImpl.java, pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/impl/PlatformDeployerBundleListener.java, pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/impl/PluginZipFileProcessor.java, pentaho-platform-plugin-deployer/src/main/resources/OSGI-INF/blueprint/blueprint.xml, pentaho-platform-plugin-deployer/src/test/java/org/pentaho/osgi/platform/plugin/deployer/impl/BundleStateManagerTest.java, pentaho-platform-plugin-deployer/src/test/java/org/pentaho/osgi/platform/plugin/deployer/impl/PlatformDeployerBundleListenerTest.java, pentaho-platform-plugin-deployer/src/test/java/org/pentaho/osgi/platform/plugin/deployer/impl/PluginZipFileProcessorTest.java
installed and uninstalled event and store the state of bundle in
BundleStateManager. PluginZipFileProcessor will only processes the
common-ui if it is not installed. Any subsequent call, it will create a
manifest and return.
- Cleaned up and applied more checkstyle fixes
- Added unit test for BundleStateManager and PlatformDeployerBundleListener
=> [BACKLOG-15673] Added bundleListener that is listening for Bundle

pentaho-object-tunnel/src/main/java/org/pentaho/osgi/objecttunnel/TunnelInput.java, pentaho-object-tunnel/src/test/java/org/pentaho/osgi/objecttunnel/TunneledInputTest.java
This is backport of https://github.com/pentaho/pentaho-osgi-bundles/pull/203 Absence of the commit is causing BACKLOG-16403.
@mkambol @pentaho-nbaker  @dkincade @mdamour1976
=> [BACKLOG-16403] AEL:java.lang.IllegalStateException: Unexpected object in stream: heartbeat when running ktr with delay 30 or more minutes

pentaho-metastore-locator/impl/local/src/main/resources/OSGI-INF/blueprint/blueprint.xml
=> [BACKLOG-17171]-[DEV] - Use existing the Metastore locator to find

pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsDependencyResolver.java, pentaho-requirejs-utils/src/main/java/org/pentaho/js/require/RequireJsGenerator.java
First commit is a bug, never detected because we never used packages with more than one module.
(We need better unit tests on these modules)
Second commit is due to D3 recently changing its choice of alternative main field in package.json (https://github.com/d3/d3/issues/3138).
Third commit, since we're at it, adds the ability to use unversioned moduleIDs on the pentaho/service, pentaho/typeInfo and pentaho/instanceInfo configurations.
=> [CLEANUP] RequireJS configuration fixes

pentaho-proxy-spring4/pom.xml
Reverts pentaho/pentaho-osgi-bundles#245
- Reverted as per the decisions made ( and captured ) at https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=336291#comment-336291
Part of a bulk-revert, comprised of the PR list captured at https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=321593#comment-321593:
@pentaho/rogueone @pamval @dkincade @mbatchelor @mdamour1976 @graimundo 
~Please **hold off merging** until we have triggered a "Revert PR" for all PRs outlined in https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=321593#comment-321593~ ✅ 
* https://github.com/pentaho/pentaho-engineering-samples/pull/61
* https://github.com/pentaho/marketplace/pull/147
* https://github.com/pentaho/data-access/pull/999
* https://github.com/pentaho/pentaho-kettle/pull/5176
* …
=> Revert "[PPP-3876]-Use of vulnerable component spring-security-core 4.1.9 cve-2017-4995"

pentaho-proxy-spring4/pom.xml
Reverts pentaho/pentaho-osgi-bundles#264
@pentaho/rogueone @pamval @dkincade @mbatchelor @mdamour1976 @graimundo
**List or PRs**
- https://github.com/pentaho/marketplace/pull/149
- https://github.com/pentaho/pentaho-metadata-editor-ee/pull/37
- https://github.com/pentaho/pentaho-metadata-editor/pull/124
- https://github.com/pentaho/pentaho-kettle/pull/5275
- https://github.com/pentaho/pentaho-platform/pull/4111
- https://github.com/pentaho/pentaho-platform-ee/pull/1266
- https://github.com/pentaho/pentaho-karaf-assembly/pull/441
- https://github.com/pentaho/pdi-ee-plugin/pull/357
- https://github.com/pentaho/pentaho-reportdesigner-ee/pull/107
- https://github.com/pentaho/pentaho-reporting/pull/1134
- https://github.com/pentaho/pentaho-osgi-bundles/pull/265
=> Revert "[BACKLOG-22526] vulnerable component spring-security: upgrade from 4.…"

pentaho-osgi-utils-api/pom.xml, pentaho-osgi-utils-impl/pom.xml, pentaho-platform-plugin-deployer/pom.xml, pom.xml
@graimundo and @Pancho7 please review.
Note that this targets pentaho:karaf_update, so wingman will not run. Our build pipeline will, when all related PRs are merged.
Needs [pentaho/maven-parent-poms#107](https://github.com/pentaho/maven-parent-poms/pull/107).
=> [BACKLOG-27577] Centralize karaf dependencies management

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/vfs/MetadataToMondrianVfs.java
@pentaho/tatooine @pentaho-lmartins @ssamora @wseyler 
* [PDI-17775] Updating file to extend AbstractFileProvider instead of implementing FileProvider (compatability for commons-vfs2-2.3). Extending also implements FileProvider.
This is a multi-pull request, please see: pentaho/pentaho-kettle#6316
=> [PDI-17775] Process Files step no longer supports HTTP scheme

pentaho-requirejs-compressor/pom.xml
@pentaho/tatooine @pentaho-lmartins @wseyler
* [PPP-4400] Remove version reference, letting maven-parent-poms handle it
This Pull Request is part of a series of Pull Requests:
- https://github.com/pentaho/maven-parent-poms/pull/145
- https://github.com/pentaho/pdi-osgi-bridge/pull/73
- https://github.com/pentaho/pdi-monitoring-plugin/pull/96
- https://github.com/pentaho/pentaho-ee/pull/2128
- https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/227
- https://github.com/pentaho/pentaho-osgi-bundles/pull/324
=> [PPP-4400] Use of Vulnerable Component: logback-classic-1.1.11.jar (CVE-2017-5929)

pentaho-requirejs-compressor/pom.xml, pentaho-requirejs-compressor/src/main/java/org/pentaho/platform/osgi/requirejs/api/IAmdScriptSource.java
@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950
This PR is a part of a set of PRs (pentaho-ee was not backported as the relevant file was added in version 8.0+):
- pentaho/maven-parent-poms#150
- pentaho/pdi-osgi-bridge#77
- pentaho/pdi-monitoring-plugin#98
- pentaho/pentaho-karaf-ee-assembly#229
- #327
=> [SP-5146] Backport of PPP-4400 - Use of Vulnerable Component: logback-classic-1.1.11.jar (CVE-2017-5929) (7.1 Suite)

pentaho-requirejs-compressor/pom.xml
@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950 
This PR is a part of a set of PRs:
- https://github.com/pentaho/maven-parent-poms/pull/149
- https://github.com/pentaho/pdi-osgi-bridge/pull/76
- https://github.com/pentaho/pdi-monitoring-plugin/pull/97
- https://github.com/pentaho/adaptive-execution-layer/pull/5
- https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/228
- https://github.com/pentaho/pentaho-osgi-bundles/pull/325
=> [SP-5147] Backport of PPP-4400 - Use of Vulnerable Component: logback-classic-1.1.11.jar (CVE-2017-5929) (8.3 Suite)

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/vfs/MetadataToMondrianVfs.java
This reverts commit d90ee1478bafcf8ac69ee6b2591b4e018ea72a92, reversing
changes made to f80f3e786025acc2f11c838ab50f972236de0049.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
=> Revert "Merge pull request #362 from gryphendowre/SP-5370"

pentaho-platform-plugin-deployer/pom.xml, pentaho-platform-plugin-deployer/src/test/java/org/pentaho/osgi/platform/plugin/deployer/impl/handlers/pluginxml/PluginXmlStaticPathsHandlerTest.java
corrections to handle missing depedencies.
=> [BACKLOG-35509] Use compiler target settings from parent pom.  Unit test

pentaho-proxy-factory/pom.xml
- removing unused dependnecy 'org.yaml:snakeyaml' from pentaho-proxy-factory
=> [PPP-5163] Vulnerable Component: snakeyaml - part 2 ( Non OSGi upgrade)

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/AgileBiAuthorizationPolicy.java, pentaho-pdi-platform/src/test/java/org/pentaho/platform/pdi/AgileBiAuthorizationPolicyTest.java
To note that this PR is not really a backport as the original error did not happen on master most probably due to the changes in the code line existing on both versions.
This is the fix for the 9.3 code line!
@pentaho/tatooine_dev
=> [SP-6624] Backport of PDI-20219 - Charts do not function in DET in 9.3.0.8 (9.3 Suite)

pentaho-pdi-platform/pom.xml
[BACKLOG-41287]-Upgrading pentaho-osgi-bundles from Java EE to Jakarta EE to support with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41287]-Upgrading pentaho-osgi-bundles from Java EE to Jakarta EE to support with Tomcat-10.X

pentaho-osgi-utils/api/pom.xml, pentaho-osgi-utils/api/src/main/java/org/pentaho/osgi/api/IKarafFeatureWatcher.java, pentaho-osgi-utils/impl/src/main/java/org/pentaho/osgi/impl/KarafFeatureWatcherImpl.java
objects outside the OSGi framework (KarafLifecycleListener) can read config settings.
=> [CUST-284] Provide external interface to read karaf config values so

pentaho-osgi-utils/api/src/main/java/org/pentaho/osgi/api/IKarafFeatureWatcher.java, pentaho-osgi-utils/impl/src/main/java/org/pentaho/osgi/impl/KarafFeatureWatcherImpl.java
objects outside the OSGi framework (KarafLifecycleListener) can read config settings.
=> [BACKLOG-42944] Provide external interface to read karaf config values so

pentaho-pdi-platform/pom.xml
**⚠️ Merge only after https://github.com/pentaho/maven-parent-poms/pull/761 has been merged ⚠️** 
This pull request includes a minor dependency update in the `pentaho-pdi-platform/pom.xml` file. The change updates the version reference for the `gwt-servlet-jakarta` dependency to use the `${gwt.version}` property instead of `${gwt-servlet-jakarta.version}`.
=> build[PPP-5751]: update GWT version to 2.12.2 and adjust groupId for GWT dependencies
