pentaho/pentaho-osgi-bundles

pentaho-osgi-utils-api/src/main/java/org/pentaho/osgi/api/ProxyUnwrapper.java
pentaho-osgi-utils-impl/pom.xml
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/BeanFactoryActivator.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/ProxyUnwrapperImpl.java

[BACKLOG-312] - Updating to allow for unwrapping of proxied objects

[BACKLOG-312] - Updating to allow for unwrapping of proxied objects

---

.gitignore
pentaho-cache-manager/api/pom.xml
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/Constants.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheManager.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheProvidingService.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheSystemConfiguration.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheTemplateConfiguration.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/impl/PentahoCacheManagerFactory.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/impl/PentahoCacheManagerImpl.java
pentaho-cache-manager/api/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/api/PentahoCacheManagerTest.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/api/PentahoCacheSystemConfigurationTest.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/impl/PentahoCacheManagerFactoryTest.java
pentaho-cache-manager/impl/RI/pom.xml
pentaho-cache-manager/impl/RI/src/main/java/org/pentaho/caching/ri/HeapCacheProvidingService.java
pentaho-cache-manager/impl/RI/src/main/java/org/pentaho/caching/ri/impl/GuavaCacheManager.java
pentaho-cache-manager/impl/RI/src/main/java/org/pentaho/caching/ri/impl/WrappedCache.java
pentaho-cache-manager/impl/RI/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-cache-manager/impl/RI/src/test/java/org/pentaho/caching/ri/HeapCacheProvidingServiceTest.java
pentaho-cache-manager/impl/RI/src/test/java/org/pentaho/caching/ri/impl/GuavaCacheManagerTest.java
pentaho-cache-manager/impl/RI/src/test/java/org/pentaho/caching/ri/impl/WrappedCacheTest.java
pentaho-cache-manager/pom.xml
pom.xml

Initial implementation of Pentaho Cache Manager
@CodeOnCoffee @deinspanjer

Pentaho Cache Manager

---

pentaho-cache-manager/api/pom.xml
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/Constants.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheManager.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheProvidingService.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheSystemConfiguration.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheTemplateConfiguration.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/impl/PentahoCacheManagerFactory.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/impl/PentahoCacheManagerImpl.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/spi/AbstractCacheManager.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/spi/AbstractCacheProvidingService.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/api/PentahoCacheManagerTest.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/api/PentahoCacheSystemConfigurationTest.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/impl/PentahoCacheManagerFactoryTest.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/spi/AbstractCacheManagerTest.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/spi/AbstractCacheProvidingServiceTest.java
pentaho-cache-manager/impl/RI/src/main/java/org/pentaho/caching/ri/HeapCacheProvidingService.java
pentaho-cache-manager/impl/RI/src/main/java/org/pentaho/caching/ri/impl/GuavaCacheManager.java
pentaho-cache-manager/impl/RI/src/main/java/org/pentaho/caching/ri/impl/WrappedCache.java
pentaho-cache-manager/impl/RI/src/test/java/org/pentaho/caching/ri/HeapCacheProvidingServiceTest.java
pentaho-cache-manager/impl/RI/src/test/java/org/pentaho/caching/ri/impl/GuavaCacheManagerTest.java
pentaho-cache-manager/impl/RI/src/test/java/org/pentaho/caching/ri/impl/WrappedCacheTest.java

* Abstract cache implementation classes
* Default template
* TTL eviction
@pentaho-nbaker @mkambol

Backlog 2831,3441

---

pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/Constants.java
pentaho-cache-manager/api/src/main/java/org/pentaho/caching/spi/AbstractCacheProvidingService.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/spi/AbstractCacheProvidingServiceTest.java

[BACKLOG-3358]  Adding storeByValue as a configurable setting.

---

pentaho-cache-manager/pom.xml

[BACKLOG-3358]  Added ehcache module to parent pom.

---

pentaho-cache-manager/api/src/main/java/org/pentaho/caching/api/PentahoCacheTemplateConfiguration.java
pentaho-cache-manager/api/src/test/java/org/pentaho/caching/api/PentahoCacheTemplateConfigurationTest.java

associated with a template.
This will be used to dynamically set things like TTL.
@hudak

[BACKLOG-4246] Introduced a method to allow overriding properties

---

pentaho-cache-manager/impl/ehcache/src/main/java/org/pentaho/caching/ehcache/EhcacheProvidingService.java

ehCache jCache Manager
@pentaho-nbaker

[BISERVER-12773] Ensuring all threads created will be daemon

---

pentaho-osgi-utils-api/src/main/java/org/pentaho/osgi/api/BlueprintStateService.java
pentaho-osgi-utils-api/src/main/java/org/pentaho/osgi/api/IKarafBlueprintWatcher.java
pentaho-osgi-utils-impl/pom.xml
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/BeanFactoryActivator.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/BlueprintStateServiceImpl.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafBlueprintWatcherImpl.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafFeatureWatcherImpl.java

[BACKLOG-5061] Wait for all blueprint services to load in Karaf

---

pentaho-osgi-utils-api/src/main/java/org/pentaho/osgi/api/BlueprintStateService.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/BlueprintStateServiceImpl.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafBlueprintWatcherImpl.java

[BACKLOG-5061] Added checked for failed blueprints

---

pentaho-proxy-spring4/src/test/java/org/pentaho/proxy/spring4/UserDetailsServiceImplTest.java

[CLEANUP] Unit test fix

---

pentaho-osgi-utils-impl/pom.xml
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafFeatureWatcherImpl.java
pentaho-service-coordinator/src/main/java/org/pentaho/platform/servicecoordination/api/IServiceBarrierManager.java
pentaho-service-coordinator/src/main/java/org/pentaho/platform/servicecoordination/impl/ServiceBarrierManager.java
pentaho-service-coordinator/src/test/java/org/pentaho/platform/servicecoordination/impl/ServiceBarrierManagerTest.java

Reverts pentaho/pentaho-osgi-bundles#71

Revert "[BACKLOG-5526] Add Periodic status logging and ServerStatusProvider"

---

pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnection.java
pentaho-webjars-deployer/src/test/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnectionTest.java

JarOutputStream and added closing instructions for the input stream.

[PDI-14520] Add "catch"s for exceptions resulting from the close of the

---

pentaho-osgi-utils-impl/pom.xml
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafFeatureWatcherImpl.java
pentaho-service-coordinator/pom.xml
pentaho-service-coordinator/src/main/java/org/pentaho/platform/servicecoordination/api/IServiceBarrierManager.java
pentaho-service-coordinator/src/test/java/org/pentaho/platform/servicecoordination/impl/ServiceBarrierManagerIntegrationTest.java
pentaho-service-coordinator/src/test/java/org/pentaho/platform/servicecoordination/impl/ServiceBarrierManagerTest.java
pentaho-service-coordinator/src/test/java/org/pentaho/platform/servicecoordination/impl/ServiceBarrierThreadTest.java

Waits for the jcrRepository Bean to be created before starting the the Karaf 2 minute timeout in KarafFeatureWatcherImpl

[BACKLOG-5858] Introduce ServiceBarrier backed BarrierBeans

---

pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsConfigManager.java
pentaho-requirejs-osgi-manager/src/test/java/org/pentaho/js/require/RequireJsConfigManagerTest.java

[MARKET-339] Remove syncronized block and use Future cancelation

---

pentaho-osgi-utils-api/pom.xml
pentaho-osgi-utils-api/src/main/java/org/pentaho/osgi/api/BlueprintStateService.java
pentaho-osgi-utils-impl/pom.xml
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/BlueprintStateServiceImpl.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafBlueprintWatcherImpl.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafFeatureWatcherImpl.java
pentaho-osgi-utils-impl/src/test/java/org/pentaho/osgi/impl/BlueprintStateServiceImplTest.java
pentaho-osgi-utils-impl/src/test/java/org/pentaho/osgi/impl/KarafBlueprintWatcherImplTest.java
pentaho-osgi-utils-impl/src/test/java/org/pentaho/osgi/impl/KarafFeatureWatcherImplTest.java
pentaho-osgi-utils-impl/src/test/java/org/pentaho/osgi/impl/WatchersTestUtils.java

initialization to Karaf Feature and Karaf Blueprint Watchers.

[BACKLOG-7244] Added debug output when error occur in OSGI

---

pentaho-requirejs-utils/src/test/resources/pom.xml

org.pentaho.js.require.RequireJsGeneratorTest.testConfigFromPom will
pass.

[TEST] Reverted test resource pom.xml to its original content so test

---

pentaho-authentication-mapper/api/pom.xml
pentaho-authentication-mapper/api/src/main/java/org/pentaho/authentication/mapper/api/AuthenticationMappingService.java
pentaho-authentication-mapper/impl/src/test/java/org/pentaho/authentication/mapper/impl/AuthenticationMappingManagerImplTest.java

[BACKLOG-7584]Remove default method from AuthenticationMappingService

---

pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsConfigManager.java
pentaho-requirejs-osgi-manager/src/test/java/org/pentaho/js/require/RequireJsConfigManagerTest.java
pentaho-requirejs-osgi-manager/src/test/resources/org/pentaho/js/require/RequireJsConfigManagerTest.testExternalStaticResources.json
pentaho-requirejs-osgi-manager/src/test/resources/org/pentaho/js/require/RequireJsConfigManagerTest.testPackages.json
pentaho-requirejs-osgi-manager/src/test/resources/org/pentaho/js/require/RequireJsConfigManagerTest.testStaticResources.internal
pentaho-requirejs-osgi-manager/src/test/resources/org/pentaho/js/require/RequireJsConfigManagerTest.testStaticResources.json
pentaho-ss2-proxies/src/test/java/org/pentaho/proxy/creators/ProxyUtilsTest.java

[BACKLOG-8625] - RequireJS bundle uninstall cache reload. JUnit testing to increase code coverage. Copyright fix.

[BACKLOG-8625] - RequireJS bundle uninstall cache reload. JUnit testing to increase code coverage. Copyright fix.

---

pentaho-i18n-bundle/example/src/main/resources/i18n/test/messages.properties
pentaho-i18n-bundle/example/src/main/resources/i18n/test/messages_fr.properties
pentaho-i18n-bundle/example/src/main/resources/i18n/test/messages_pt.properties
pentaho-i18n-bundle/example/src/main/resources/web/i18n.html

- Added sample page
- Added test message.properties

[BACKLOG-9131] - Add AMD i18n service to the i18n bundle

---

pentaho-notification-webservice-bundle/pom.xml

@lgrill-pentaho  allows tests to run again

[BACKLOG-9280] added property for jasmine.serverPort

---

pentaho-spring-dm-extender/pom.xml
pentaho-spring-dm-extender/src/main/java/org/pentaho/springdm/extender/ApplicationContextCreator.java
pentaho-spring-dm-extender/src/main/java/org/pentaho/springdm/extender/PentahoOsgiBundleXmlApplicationContext.java

[CLEANUP] - removing references to commons-logging objects in favor of slf4j

[CLEANUP] - removing references to commons-logging objects in favor of slf4j

---

pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/KarafBlueprintWatcherImpl.java
pentaho-osgi-utils-impl/src/test/java/org/pentaho/osgi/impl/KarafBlueprintWatcherImplTest.java

#122 
@mbatchelor please review

[SP-2845] Backport of PDI-14698 - Bundles sometimes fail to come up in Karaf (6.1 Suite)

---

pentaho-notification-webservice-bundle/pom.xml
pentaho-notification-webservice-bundle/src/test/resources/js/notifierTest.js

@pamval @diogofscmariano Please review.

[FIX] - Removed broken js tests and common-ui dependency.

---

angular-bundle/pom.xml
angular-bundle/src/main/resources/META-INF/js/require.json
angular-bundle/src/main/resources/OSGI-INF/blueprint/blueprint.xml
angular-bundle/src/main/resources/js/angular-resource.js
angular-bundle/src/main/resources/js/angular-route.js
angular-bundle/src/main/resources/js/angular.js
pentaho-requirejs-osgi-manager/src/test/java/org/pentaho/js/require/RequireJsConfigManagerTest.java
pentaho-requirejs-osgi-manager/src/test/resources/org/pentaho/js/require/RequireJsConfigManagerTest.testGetRequireJsConfig.json
pentaho-requirejs-osgi-manager/src/test/resources/org/pentaho/js/require/RequireJsConfigManagerTest.testGetRequireJsConfigRel.abs.json
pentaho-requirejs-osgi-manager/src/test/resources/org/pentaho/js/require/RequireJsConfigManagerTest.testGetRequireJsConfigRel.rel.json
pom.xml

Reverts pentaho/pentaho-osgi-bundles#152

Revert "[PPP-3559] - Use of vulnerable component Angular.js 1.2.15 CVE-2015-0167"

---

pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/impl/PluginZipFileProcessor.java
pentaho-requirejs-utils/src/main/java/org/pentaho/js/require/RequireJsGenerator.java

@mbatchelor, @pamval, could you please take a look?  
master's is here: https://github.com/pentaho/pentaho-osgi-bundles/pull/158

[PPP-3506] - XXE Security Vulnerability in xml parsers

---

pentaho-notification-webservice-bundle/pom.xml
pentaho-notification-webservice-bundle/src/test/resources/js/notifierTest.js

@pamval, @mbatchelor, here is the backport of https://github.com/pentaho/pentaho-osgi-bundles/commit/4b7f42bab37aa57e95392a745dd3cccd8e505777 to 6.1. Thanks.

[SP-2974] - CLEANUP - Removed broken js tests and common-ui dependency.

---

pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnection.java

[BACKLOG-7917] Fix path separator mismatch on windows

---

pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsConfigServlet.java
pentaho-requirejs-osgi-manager/src/test/java/org/pentaho/js/require/RequireJsConfigServletTest.java

[BACKLOG-13736] Better integration with webcontext.js legacy configurations

---

pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnection.java

[BACKLOG-7917] Fix yet another path separator mismatch on windows

---

pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsDependencyResolver.java
pentaho-requirejs-osgi-manager/src/test/resources/require.meta.json
pentaho-requirejs-osgi-manager/src/test/resources/require.resolved.json

[BACKLOG-13736] Workaround enabling dependencies' versions with qualifiers

---

pentaho-object-tunnel/src/main/java/org/pentaho/osgi/objecttunnel/TunnelMarker.java

[BACKLOG-14633]Define TunnelMarker for end of stream

---

pentaho-object-tunnel/src/main/java/org/pentaho/osgi/objecttunnel/TunnelInput.java
pentaho-object-tunnel/src/main/java/org/pentaho/osgi/objecttunnel/TunnelMarker.java
pentaho-object-tunnel/src/test/java/org/pentaho/osgi/objecttunnel/TunneledInputTest.java

[BACKLOG-14633]Close TunnelInput when END is encountered

---

pentaho-i18n-webservice-bundle/pom.xml
pom.xml

@diogofscmariano @CodeOnCoffee please review

[BACKLOG-14734] - Added workaround by explicitly importing org.apache.felix.http.api package.

---

pentaho-object-tunnel/src/main/java/org/pentaho/osgi/objecttunnel/TunnelInput.java
pentaho-object-tunnel/src/test/java/org/pentaho/osgi/objecttunnel/TunneledInputTest.java
pentaho-osgi-utils-api/src/main/java/org/pentaho/osgi/api/BeanFactoryLocator.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/BeanFactoryBlueprintImpl.java
pentaho-osgi-utils-impl/src/main/java/org/pentaho/osgi/impl/BeanFactoryLocatorImpl.java

Also fixing unit test which had a timing problem.

Adding support for supplemental plugin mappings.

---

pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsConfigManager.java
pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsConfigServlet.java

[BACKLOG-15657] - Added cache control for the osgi require configurations.

---

pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/impl/PluginZipFileProcessor.java

- Shamelessly copied @DFieldFL  warning from https://github.com/pentaho/pentaho-osgi-bundles/pull/189/files#diff-f63dabfe2c8144d25bde07445134d32eR202
- Added some logging
Please await for @pedrofvteixeira validation before merge.
@pedrofvteixeira @nantunes @DFieldFL @CodeOnCoffee please review

[BACKLOG-15831][CLEANUP] - Removed necessary processing.

---

pentaho-blueprint-collection-utils/src/main/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMap.java
pentaho-blueprint-collection-utils/src/test/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMapTest.java
pentaho-metastore-locator/api/src/main/java/org/pentaho/osgi/metastore/locator/api/MetastoreLocator.java
pentaho-metastore-locator/api/src/main/java/org/pentaho/osgi/metastore/locator/api/impl/MetastoreLocatorImpl.java
pentaho-metastore-locator/api/src/test/java/org/pentaho/osgi/metastore/locator/api/impl/MetastoreLocatorImplTest.java
pentaho-metastore-locator/impl/local/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-metastore-locator/impl/repository/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Reverts pentaho/pentaho-osgi-bundles#217

Revert "Revert "[BACKLOG-17014]  Provide key driven Mulit-provider MetastoreLocator""

---

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/WebContextServlet.java
pentaho-pdi-platform/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-pdi-platform/src/test/java/org/pentaho/platform/pdi/WebContextServletTest.java
pentaho-requirejs-osgi-manager/src/main/java/org/pentaho/js/require/RequireJsConfigServlet.java
pentaho-requirejs-osgi-manager/src/test/java/org/pentaho/js/require/RequireJsConfigServletTest.java

[BACKLOG-17293] Included config for 'pentaho/context' module

---

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/WebContextServlet.java
pentaho-pdi-platform/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-pdi-platform/src/test/java/org/pentaho/platform/pdi/WebContextServletTest.java

[BACKLOG-17196] Adding cxf endpoint to pentaho/context module configuration

---

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/WebContextServlet.java
pentaho-pdi-platform/src/test/java/org/pentaho/platform/pdi/WebContextServletTest.java

[BACKLOG-17190] Adding osgiRoot property to access osgi resources

---

pentaho-i18n-webservice-bundle/src/main/java/org/pentaho/osgi/i18n/webservice/ResourceBundleMessageBodyWriter.java

@pentaho/bobafett please review

[BACKLOG-17490] Added UTF-8 encoding for bundle properties

---

pentaho-webpackage/assemblies/pentaho-webpackage/src/main/feature/feature.xml
pom.xml

- forced using overridden feature descriptors by specifying their exact version in every other descriptor with their usage

[PPP-3850] Enforce resolve order for overridden feature descriptors

---

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/WebContextServlet.java

[BACKLOG-19272] Include context scripts after the requirejs configuration

---

pentaho-capability-manager/README.md
pentaho-object-tunnel/README.md
pentaho-spring-security-provider/README.md
pentaho-zookeeper-fragment/README.md

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

---

pentaho-i18n-bundle/example/src/main/resources/web/angular.html
pentaho-i18n-bundle/example/src/main/resources/web/i18n.html
pentaho-i18n-bundle/example/src/main/resources/web/index.html

[BACKLOG-19912] Changed call to requirejs-init to webcontext

---

pentaho-osgi-utils-impl/pom.xml
pentaho-pdi-platform/pom.xml
pentaho-proxy-factory/pom.xml
pentaho-server-bundle/pom.xml
pom.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-1757] version name consolidation

---

pentaho-requirejs-osgi-manager/pom.xml
pentaho-requirejs-utils/pom.xml
pentaho-webjars-deployer/pom.xml

[BACKLOG-21151] Remove direct felix framework references

---

pentaho-webcontext/assemblies/pentaho-webcontext/pom.xml
pentaho-webcontext/assemblies/pentaho-webcontext/src/main/feature/feature.xml
pentaho-webcontext/assemblies/pom.xml
pentaho-webcontext/core/impl/pom.xml
pentaho-webcontext/core/impl/src/main/java/org/pentaho/webcontext/core/impl/PentahoWebContextServletImpl.java
pentaho-webcontext/core/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-webcontext/core/impl/src/test/java/org/pentaho/webcontext/core/impl/PentahoWebContextServletImplTest.java
pentaho-webcontext/core/pom.xml
pentaho-webcontext/pom.xml
pom.xml

[BACKLOG-21716] Created Pentaho WebContext Servlet

---

pentaho-webcontext/assemblies/pentaho-webcontext/pom.xml

@pentaho/millenniumfalcon and @emartin-pentaho please review.

[BACKLOG-21716] Change dependency fixed version

---

pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/utils/RequireJsDependencyResolver.java

[BACKLOG-21716] Fix dependency resolver being order dependent

---

pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/listeners/RequireJsBundleListener.java
pentaho-webpackage/core/impl/src/main/java/org/pentaho/webpackage/core/impl/osgi/PentahoWebPackageBundleListener.java
pentaho-webpackage/core/impl/src/test/java/org/pentaho/webpackage/core/impl/osgi/PentahoWebPackageBundleListenerTest.java
pentaho-webpackage/listeners/http/src/main/java/org/pentaho/webpackage/extender/http/impl/PentahoWebPackageResourceMapping.java

[BACKLOG-23738] Prevent NPE after bundle listener is unregistered

---

pentaho-authentication-mapper/impl/pom.xml
pentaho-cache-manager/impl/ehcache/pom.xml
pentaho-notification-webservice-bundle/pom.xml
pentaho-requirejs-compressor/pom.xml
pom.xml

Reverts pentaho/pentaho-osgi-bundles#268

Revert "[PPP-4108] - Use of vulnerable component jackson-databind-2.8.8.jar, …"

---

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/WebContextServlet.java
pentaho-pdi-platform/src/test/java/org/pentaho/platform/pdi/WebContextServletTest.java
pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/plugins/ModulesInfoPluginConfig.java
pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/types/MetaInfPackageJson.java
pentaho-requirejs-osgi-manager/core/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-requirejs-osgi-manager/core/impl/src/test/java/org/pentaho/requirejs/impl/plugins/ModulesInfoPluginConfigTest.java
pentaho-requirejs-osgi-manager/core/impl/src/test/resources/org/pentaho/requirejs/impl/lib2-require.json
pentaho-webcontext/core/impl/src/main/java/org/pentaho/webcontext/core/impl/PentahoWebContextServletImpl.java
pentaho-webcontext/core/impl/src/test/java/org/pentaho/webcontext/core/impl/PentahoWebContextServletImplTest.java
pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/utils/RequireJsGenerator.java
pentaho-webpackage/deployers/archive-deployer/src/test/resources/my-simple-module-1.4.0/package.json
pentaho-webpackage/deployers/archive-deployer/src/test/resources/package.json

[BACKLOG-23466] Add `webcontext.js?application=foo` query string parameter.

---

pentaho-osgi-utils-impl/pom.xml
pentaho-proc-governor/impl/.gitignore
pentaho-proc-governor/impl/README.md
pentaho-proc-governor/impl/pom.xml
pentaho-proc-governor/impl/src/main/java/org/hitachivantara/process/ProcessGovernor.java
pentaho-proc-governor/impl/src/main/java/org/hitachivantara/process/ProcessGovernorImpl.java
pentaho-proc-governor/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-proc-governor/impl/src/test/java/org/hitachivantara/process/ProcessGovernorImplTest.java
pentaho-proc-governor/impl/src/test/resources/log4j.properties
pentaho-proc-governor/pom.xml
pom.xml

https://jira.pentaho.com/browse/BACKLOG-23929

[BACKLOG-23929] First pass at a process handler for managing ext procs.

---

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/WebContextServlet.java
pentaho-pdi-platform/src/test/java/org/pentaho/platform/pdi/WebContextServletTest.java
pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/plugins/ModulesInfoPluginConfig.java
pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/servlet/RequireJsConfigServlet.java
pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/types/MetaInfPackageJson.java
pentaho-requirejs-osgi-manager/core/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-requirejs-osgi-manager/core/impl/src/test/java/org/pentaho/requirejs/impl/plugins/ModulesInfoPluginConfigTest.java
pentaho-requirejs-osgi-manager/core/impl/src/test/resources/org/pentaho/requirejs/impl/lib2-require.json
pentaho-webcontext/core/impl/src/main/java/org/pentaho/webcontext/core/impl/PentahoWebContextServletImpl.java
pentaho-webcontext/core/impl/src/test/java/org/pentaho/webcontext/core/impl/PentahoWebContextServletImplTest.java
pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/utils/RequireJsGenerator.java
pentaho-webpackage/deployers/archive-deployer/src/test/resources/my-simple-module-1.4.0/package.json
pentaho-webpackage/deployers/archive-deployer/src/test/resources/package.json

@pentaho/millenniumfalcon please *squash and merge*.
Merge with: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1302.

[BACKLOG-23466] Refactor VizAPI module system.

---

pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.bower/angular-animate/1.5.8/overrides.json

[BACKLOG-24783] Adds org.webjars.bower/angular-animate/1.5.8 shim config

---

pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.bower/angular-route/1.5.8/overrides.json
pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.bower/angular-sanitize/1.5.8/overrides.json
pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.bower/angular-ui-bootstrap-bower/1.3.3/overrides.json

[BACKLOG-24937] angular-route, angular-sanitize and angular-ui-bootstrap-bower shim overrides (for marketplace)

---

pentaho-webpackage/pom.xml

This is a series of PRs, please see pentaho/maven-parent-poms#82 for full list.
@ssamora

[PPP-4226] Use of vulnerable component commons-compress  CVE-2018-11771

---

pentaho-osgi-utils-impl/pom.xml

[BACKLOG-27564] Centralize Aries Blueprint dependency management

---

pentaho-service-coordinator/pom.xml

[BACKLOG-27568] Centralize pax-url-aether dependency management

---

pentaho-bundle-resource-manager/pom.xml
pentaho-cache-manager/api/pom.xml
pentaho-cache-manager/pom.xml
pentaho-osgi-utils-impl/pom.xml
pentaho-osgi-utils-impl/src/test/java/org/pentaho/osgi/impl/KarafFeatureWatcherImplTest.java
pentaho-pdi-platform/pom.xml
pentaho-requirejs-osgi-manager/pom.xml
pentaho-server-bundle/pom.xml
pentaho-spring-dm-extender/pom.xml
pentaho-webjars-deployer/pom.xml
pentaho-webpackage/pom.xml
pom.xml

[BACKLOG-27567] Centralize org.osgi dependencies management

---

pentaho-requirejs-osgi-manager/core/impl/pom.xml

[BACKLOG-27567] Fix missing org.osgi.compendium dependency

---

pentaho-osgi-utils-impl/pom.xml

[BACKLOG-27571] - Removed unused property.

---

pentaho-i18n-webservice-bundle/pom.xml
pentaho-pdi-platform/pom.xml
pentaho-server-bundle/pom.xml
pentaho-webpackage/listeners/http/pom.xml
pentaho-webpackage/pom.xml
pom.xml

[BACKLOG-27569] Centralize pax-web dependency management

---

pentaho-i18n-bundle/pom.xml
pentaho-platform-plugin-deployer/pom.xml
pentaho-webjars-deployer/pom.xml
pentaho-webpackage/pom.xml
pom.xml

[BACKLOG-27572] Centralize felix-fileinstall dependency management

---

pentaho-i18n-webservice-bundle/pom.xml
pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnection.java
pom.xml

[BACKLOG-27574] Remove Felix HTTP dependency

---

pentaho-server-bundle/pom.xml
pom.xml

Needs https://github.com/pentaho/maven-parent-poms/pull/109.
@graimundo

[BACKLOG-27565] Remove unneeded cxf-rt-frontend-jaxrs dependency

---

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/vfs/MetadataToMondrianVfs.java

Reverts pentaho/pentaho-osgi-bundles#315

Revert "[PDI-17775] Process Files step no longer supports HTTP scheme"

---

pentaho-authentication-mapper/impl/pom.xml
pentaho-bundle-resource-manager/pom.xml
pentaho-capability-manager/pom.xml
pentaho-i18n-bundle/pom.xml
pentaho-kettle-repository-locator/impl/platform/pom.xml
pentaho-metastore-locator/api/pom.xml
pentaho-metastore-locator/impl/local/pom.xml
pentaho-metastore-locator/impl/repository/pom.xml
pentaho-osgi-utils-impl/pom.xml
pentaho-pdi-platform/pom.xml
pentaho-platform-plugin-deployer/pom.xml
pentaho-proc-governor/impl/pom.xml
pentaho-proxy-factory/pom.xml
pentaho-proxy-spring4/pom.xml
pentaho-requirejs-compressor/pom.xml
pentaho-requirejs-osgi-manager/core/impl/pom.xml
pentaho-requirejs-osgi-manager/pom.xml
pentaho-server-bundle/pom.xml
pentaho-service-coordinator/pom.xml
pentaho-spring-dm-extender/pom.xml
pentaho-spring-security-provider/pom.xml
pentaho-webjars-deployer/pom.xml
pentaho-webpackage/core/impl/pom.xml
pentaho-webpackage/listeners/http/pom.xml
pentaho-webpackage/listeners/requirejs/pom.xml
pentaho-webpackage/pom.xml
pom.xml

Needs https://github.com/pentaho/maven-parent-poms/pull/111
@graimundo

[BACKLOG-27566] Centralize SLF4J dependency

---

pentaho-i18n-bundle/src/main/java/org/pentaho/osgi/i18n/impl/LocalizationManager.java
pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/listeners/RequireJsBundleListener.java
pentaho-requirejs-osgi-manager/core/impl/src/test/java/org/pentaho/requirejs/impl/types/MetaInfRequireJsonTest.java
pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/utils/RequireJsGenerator.java
pentaho-webjars-deployer/src/test/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnectionTest.java
pentaho-webjars-deployer/src/test/java/org/pentaho/osgi/platform/webjars/utils/RequireJsGeneratorTest.java
pentaho-webpackage/core/impl/src/main/java/org/pentaho/webpackage/core/impl/PentahoWebPackageImpl.java
pentaho-webpackage/deployers/archive-deployer/src/main/java/org/pentaho/webpackage/deployer/archive/impl/WebPackageURLConnection.java

[BACKLOG-26046] Fix usage of JSONParser because it is NOT thread-safe

---

pax-logging-api-wrap/README.md
pax-logging-api-wrap/pom.xml
pentaho-webpackage/core/impl/pom.xml
pentaho-webpackage/deployers/archive-deployer/pom.xml
pom.xml

[karaf_update] Wrap pax-logging-api

---

pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnection.java
pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/WebjarsUrlHandler.java
pentaho-webjars-deployer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.bower/angular-translate/2.12.1/overrides.json
pentaho-webjars-deployer/src/test/java/org/pentaho/osgi/platform/webjars/WebjarsURLConnectionTest.java

Makes the webjars minification and the automatic AMD shim config of nom-AMD packages optional and disabled by default.
@graimundo and @pentaho/millenniumfalcon please review.

[BACKLOG-31820] Optimize pentaho-webjars-deployer

---

pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.npm/jquery/3.4.0/overrides.json
pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.npm/underscore/1.8.3/overrides.json

[BACKLOG-31820] jquery and underscore webjar package config overrides

---

pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.npm/react-dom/16.9.0/overrides.json
pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.npm/react/16.9.0/overrides.json

Merge along with: https://github.com/pentaho/layout-editor/pull/188.

[BACKLOG-30968] Adding Web Jar overrides for react and react-dom.

---

pentaho-bundle-resource-manager/src/main/java/org/pentaho/osgi/manager/resource/BundleResourceListener.java

[BACKLOG-31940] Only copy bundle managed resources when at the resolved stage

---

pentaho-blueprint-collection-utils/src/main/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMap.java
pentaho-blueprint-collection-utils/src/test/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMapTest.java

@pentaho/tatooine 
@pentaho-lmartins 
@mkambol

[PDI-18430] - Parallel job entry execution can result in NPE

---

pentaho-blueprint-collection-utils/src/main/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMap.java
pentaho-blueprint-collection-utils/src/test/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMapTest.java

Fixing issue introduced by 619368104986258ea5520ddc03c8433eebbc7756

[PDI-18430]  Null keys are allowed by ServiceMap.getItem.

---

pentaho-blueprint-collection-utils/src/main/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMap.java
pentaho-blueprint-collection-utils/src/test/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMapTest.java

**Attention: This is the outcome of an automated process!**
Merge Masters: @pentaho-lmartins and 
Cherry-picks:
* https://github.com/Pentaho/pentaho-osgi-bundles/commit/619368104986258ea5520ddc03c8433eebbc7756
* https://github.com/Pentaho/pentaho-osgi-bundles/commit/256c89bcc86167e20889f4afc6c88f11c9a7c9d2

[SP-5438] Backport of PDI-18430 - Parallel job entry execution can result in NPE (8.3 Suite)

---

pentaho-blueprint-collection-utils/src/main/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMap.java
pentaho-blueprint-collection-utils/src/test/java/org/pentaho/osgi/blueprint/collection/utils/ServiceMapTest.java

**Attention: This is the outcome of an automated process!**
Merge Masters: @pentaho-lmartins and 
Cherry-picks:
* https://github.com/Pentaho/pentaho-osgi-bundles/commit/619368104986258ea5520ddc03c8433eebbc7756
* https://github.com/Pentaho/pentaho-osgi-bundles/commit/256c89bcc86167e20889f4afc6c88f11c9a7c9d2

[SP-5439] Backport of PDI-18430 - Parallel job entry execution can result in NPE (9.0 Suite)

---

pentaho-webjars-deployer/src/main/resources/overrides/org.webjars.bower/angular-ui-router/0.4.2/overrides.json

Reverts pentaho/pentaho-osgi-bundles#359
@pentaho/r2d2 
@pentaho/millenniumfalcon

Revert "[BACKLOG-33388] making both ui-router libraries available for angular…"

---

spring-kafka/api/pom.xml
spring-kafka/api/src/main/java/org/hitachivantara/spring/kafka/producer/BaseMessageProducer.java
spring-kafka/api/src/main/java/org/hitachivantara/spring/kafka/producer/KafkaProducerFactory.java

Adds a bundle so that we can reuse some of the Kafka initialization code in Worker Nodes.
Merge along with https://github.com/pentaho/pdi-plugins-ee/pull/217

[BACKLOG-33939] Refactor Kafka code for better reuse

---

spring-kafka/README.md

[TAP-559] Add a README.md on how to use Spring Kafka

---

pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/servlet/RequireJsConfigServlet.java
pentaho-requirejs-osgi-manager/core/impl/src/test/java/org/pentaho/requirejs/impl/servlet/RequireJsConfigServletTest.java

@pentaho-lmartins 
@ssamora 
@smmribeiro

[BISERVER-14464] - Marketplace is not available when accessed via load balancer or proxy server

---

pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/RequireJsConfigManager.java
pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/servlet/RequireJsConfigServlet.java
pentaho-requirejs-osgi-manager/core/impl/src/test/java/org/pentaho/requirejs/impl/servlet/RequireJsConfigServletTest.java

@pentaho-lmartins 
@ssamora 
@smmribeiro

SP-5780 Backport of BISERVER-14464 - Marketplace is not available when accessed via load balancer or proxy server (9.1 Suite)

---

pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/RequireJsConfigManager.java
pentaho-requirejs-osgi-manager/core/impl/src/main/java/org/pentaho/requirejs/impl/servlet/RequireJsConfigServlet.java
pentaho-requirejs-osgi-manager/core/impl/src/test/java/org/pentaho/requirejs/impl/servlet/RequireJsConfigServletTest.java

@pentaho-lmartins 
@ssamora 
@smmribeiro

[SP-5779] - Backport of BISERVER-14464 - Marketplace is not available when accessed via load balancer or proxy server (8.3 Suite)

---

.gitignore
pentaho-osgi-utils/impl/pom.xml
pentaho-osgi-utils/impl/src/test/java/org/pentaho/osgi/impl/KarafBlueprintWatcherImplTest.java
pentaho-osgi-utils/impl/src/test/java/org/pentaho/osgi/impl/KarafFeatureWatcherImplTest.java
pentaho-osgi-utils/impl/src/test/java/org/pentaho/osgi/impl/LogUtil.java

[BISERVER-14720] Upgrade log4j2

---

pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/XmiToDatabaseMetaDatasourceService.java

connections when the connection is defined using variables.

[PDI-18826] Pentaho platform needs to be able to provide pooled DB

---

pom.xml

this is for the backporting from the original commit - ec31bd91b1bc5e1e66b63932bec8e9549a433b42

[PPP-4654] Get commons-io version from parent pom

---

pom.xml

@smmribeiro 
@andreramos89 
@renato-s

[PPP-4755] - Vulnerable Component: Spring 5.3.3

---

pom.xml

[SP-6229] - Backport of PPP-4755 - Vulnerable Component: Spring 5.3.3(9.3 Suite)

---

pentaho-proxy-spring4/pom.xml

@smmribeiro 
@andreramos89 
@renato-s

[PPP-4758] - Vulnerable Component: Spring Security - CVE-2022-22978

---

pentaho-proxy-factory/pom.xml

[PPP-4660] - Use of Vulnerable Component: Components/jackson-databind:2.9.10.2

---

pentaho-proxy-spring4/pom.xml

@smmribeiro 
@bcostahitachivantara 
@renato-s

[SP-6264] - Backport of PPP-4758 - Vulnerable Component: Spring Security - CVE-2022-22978 (9.3 Suite)

---

pentaho-proxy-spring4/pom.xml

[SP-6265] - Backport of PPP-4758 - Vulnerable Component: Spring Security - CVE-2022-22978 (9.4 Suite)

---

pentaho-proxy-spring4/pom.xml

@smmribeiro
@andreramos89
@renato-s

[PPP-4827] - Vulnerable Component: Spring Security - CVE-2022-31692

---

pentaho-proxy-factory/pom.xml

@smmribeiro 
@bcostahitachivantara 
@renato-s

[PPP-4610] - Use of Vulnerable Component: Components/snakeyaml:1.25

---

pentaho-proxy-factory/pom.xml

[SP-6306] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.4 Suite)

---

pentaho-proxy-factory/pom.xml

[SP-6305] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.3 Suite)

---

pentaho-osgi-utils/impl/src/main/java/org/pentaho/osgi/impl/KarafFeatureWatcherImpl.java

perform extensive report generation for a debug log when the log is not set to debug mode.

[BACKLOG-37665] Check services are not null before using.  Do not

---

spring-security-karaf-login-module/src/main/java/org/pentaho/platform/osgi/auth/spring/SpringSecurityLoginModule.java
spring-security-karaf-login-module/src/test/java/org/pentaho/platform/osgi/auth/spring/SpringSecurityLoginModuleTest.java

- added necessary roles to principal in SpringSecurityLoginModule.java based on etc/users.properties
please see https://hv-eng.atlassian.net/browse/BACKLOG-37812?focusedCommentId=1771630 for demo of successfully being able to run command _feature:install_

[BACKLOG-37812] 4.X Karaf Command Not Found for feature:install

---

pom.xml

@andreramos89 
@bcostahitachivantara 
Original PR:
- https://github.com/pentaho/pentaho-osgi-bundles/pull/449

[SP-6373] - Backport of PPP-4879 - Vulnerable Component: Spring 5.3.23 (9.5 Suite)

---

pom.xml
spring-framework-features/spring32/pom.xml
spring-framework-features/spring32/src/main/feature/feature.xml

[PPP-4882] - Vulnerable Component: Spring Security - (CVE-2023-20861) after applying 9.3.0.3

---

pom.xml
spring-framework-features/spring32/pom.xml
spring-framework-features/spring32/src/main/feature/feature.xml

Original PR: [https://github.com/pentaho/pentaho-osgi-bundles/pull/450](https://github.com/pentaho/pentaho-osgi-bundles/pull/450)
@smmribeiro 
@bcostahitachivantara 
@renato-s

[SP-6383] - Backport of PPP-4882 - Vulnerable Component: Spring Security - (CVE-2023-20861) after applying 9.3.0.3 (9.3 Suite)

---

pentaho-proxy-factory/pom.xml

[PPP-4865] - Vulnerable Component: snakeyaml

---

pom.xml

[PPP-5069] Vulnerable Component: Spring

---

pom.xml

Original PR: [pentaho-osgi-bundles#469](https://github.com/pentaho/pentaho-osgi-bundles/pull/469)
@pentaho/tatooine_dev

[SP-6548] Backport of PPP-5069 - Vulnerable Component: Spring (9.3 Suite)

---

pom.xml

Original PR: [pentaho-osgi-bundles#469](https://github.com/pentaho/pentaho-osgi-bundles/pull/469)
@pentaho/tatooine_dev

[SP-6549] Backport of PPP-5069 - Vulnerable Component: Spring (10.1 Suite)

---

pentaho-osgi-utils/pom.xml

[PPP-5077]-Vulnerable Component: mina-core
[PPP-5077]: https://hv-eng.atlassian.net/browse/PPP-5077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5077]-Vulnerable Component: mina-core

---

pentaho-bundle-resource-manager/pom.xml
pentaho-cache-manager/api/pom.xml
pentaho-cache-manager/impl/ehcache/pom.xml
pentaho-i18n-bundle/pom.xml
pentaho-osgi-utils/api/pom.xml
pentaho-osgi-utils/assemblies/feature/pom.xml
pentaho-osgi-utils/impl/pom.xml
pentaho-osgi-utils/pom.xml
pentaho-pdi-platform/pom.xml
pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/BundleClassloader.java
pentaho-pdi-platform/src/main/java/org/pentaho/platform/pdi/ResourceDelegatingBundleClassLoader.java
pentaho-platform-plugin-deployer/pom.xml
pentaho-proxy-factory/pom.xml
pentaho-requirejs-osgi-manager/core/impl/pom.xml
pentaho-server-bundle/pom.xml
pentaho-service-coordinator/pom.xml
pentaho-spring-dm-extender/pom.xml
pentaho-webjars-deployer/pom.xml
pentaho-webpackage/core/impl/pom.xml
pentaho-webpackage/deployers/archive-deployer/pom.xml
pentaho-webpackage/listeners/http/pom.xml
pentaho-webpackage/listeners/requirejs/pom.xml
spring-framework-features/spring32/pom.xml
spring-framework-features/spring43/pom.xml
spring-framework-features/spring53/pom.xml
spring-security-karaf-login-module/pom.xml

(cherry picked from commit 19ef033f653dae44c1fdd9d3f7028b75a2e1a66f)

[BACKLOG-42821] - Karaf upgrade to 4.4.6 and vulnerability fixes

---

pentaho-cache-manager/impl/ehcache/pom.xml
pentaho-cache-manager/impl/ehcache/src/main/java/org/pentaho/caching/ehcache/EhcacheProvidingService.java

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

---

pentaho-proxy-spring4/pom.xml

[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43209]-OSGi Assembly Issues

---

pentaho-proxy-spring4/pom.xml

[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version
[BACKLOG-43757]: https://hv-eng.atlassian.net/browse/BACKLOG-43757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version

---

pentaho-i18n-bundle/example/src/main/resources/web/index.html

[SP-6837]-Backport of PPP-5132 - XSS Findings (10.2 Suite)
[SP-6837]: https://hv-eng.atlassian.net/browse/SP-6837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6837]-Backport of PPP-5132 - XSS Findings (10.2 Suite)

---

pentaho-osgi-utils/assemblies/feature/pom.xml
pentaho-requirejs-osgi-manager/assemblies/feature/pom.xml
pentaho-webcontext/assemblies/pentaho-webcontext/pom.xml
pentaho-webpackage/assemblies/pentaho-webpackage-archive-deployer/pom.xml
pentaho-webpackage/assemblies/pentaho-webpackage/pom.xml
spring-framework-features/spring32/pom.xml
spring-framework-features/spring43/pom.xml
spring-framework-features/spring53/pom.xml
spring-kafka/assembly/pom.xml

[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

---

pentaho-i18n-webservice-bundle/src/main/java/org/pentaho/osgi/i18n/webservice/ResourceBundleMessageBodyWriter.java
pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/impl/PluginMetadataImpl.java
pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/utils/RequireJsGenerator.java

Reverts pentaho/pentaho-osgi-bundles#535
@pentaho/tatooine_dev

Revert "fix: add proper initialization to XML parser [PPP-5719]"

---

pentaho-i18n-webservice-bundle/src/main/java/org/pentaho/osgi/i18n/webservice/ResourceBundleMessageBodyWriter.java
pentaho-platform-plugin-deployer/src/main/java/org/pentaho/osgi/platform/plugin/deployer/impl/PluginMetadataImpl.java
pentaho-webjars-deployer/src/main/java/org/pentaho/osgi/platform/webjars/utils/RequireJsGenerator.java

fix: add proper initialization to XML parser [PPP-5719]
